version: "3.8"
services: 
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - 8080:80
  server:
    build:
      context: './server'
    ports:
      - "5000:5000"
    depends_on:
      - nginx
    
  client:
    build: 
      context: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
    